"""add phone number

Revision ID: 493d56eaeced
Revises: f03fdb522591
Create Date: 2023-07-31 15:18:29.199820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493d56eaeced'
down_revision = 'f03fdb522591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
